name: blog_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fpdart: ^1.1.0
  supabase_flutter: ^2.6.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  uuid: ^4.4.2
  intl: ^0.19.0
  internet_connection_checker_plus: ^2.5.1
  hive: ^4.0.0-dev.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
